### ISSUE TITLE
WISH: Add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [samWieczorek/DAPAR#7]
I'd like to suggest that you add Add 'URL' and 'BugReports' fields to the DESCRIPTION file so that it's easier to find this GitHub repos, including from http://bioconductor.org/packages/release/bioc/html/DAPAR.html

**Comment by samWieczorek** [comment]
Yes ! Thanks for the suggestion

**Comment by samWieczorek** [comment]
Done
