### ISSUE TITLE
Is R (>= 4.0.3) required for this package, or would R (>= 4.0.0) be sufficient?

### ISSUE THREAD

**Issue by HenrikBengtsson** [samWieczorek/DAPAR#8]
Hi, I just noticed that DAPAR does not install on R 4.0.2.  I see that for [Bioc devel](http://bioconductor.org/packages/devel/bioc/html/DAPAR.html), you've still got R (>= 4.0.0) but for [Bioc release](http://bioconductor.org/packages/release/bioc/html/DAPAR.html) you've got R (>= 4.0.3).

Is R (>= 4.0.3) a hard requirement for this package?  Note that Bioconductor 3.12 does _not_ require R 4.0.3, cf. https://github.com/Bioconductor/bioconductor.org/issues/76.   I run lots of revdep checks on CRAN and Bioc packages for my 'future' package and this far DAPAR is the only one that's a blocker on R 4.0.2.

PS. Yes, I know how to upgrade to R 4.0.3; I'm thinking of all the academic cluster users etc. out there still stuck on R 4.0.0.

**Comment by samWieczorek** [comment]
Hi Henrik,
The master (development version) and release versions do not have necessarily the same R version (http://bioconductor.org/developers/package-guidelines/#version). You pointed a mistake in the devel version of DAPAR which should use the devel version of R. I will fix it soon.

By default, I stick to the last version of R for the release version of Bioconductor as it is a requirement (BioC says that the release 3.12 should work with R-4.0.3, http://bioconductor.org/install/). I have read your discussion on github/Bioconductor but I have to follow general rules for developers in Bioconductor.

But DAPAR should work with R >= 4.0.0. May I ask you how you install the packages you want to test ? There is a workaround to install DAPAR (for example) on R-4.0.2. You have to manually modify the DESCRIPTION file and change the version of R. Then, you have to rebuild the package on your computer and it will be ready to be installed on previous R versions.

Does it answer your questions ?

Best regards

Sam
De : Henrik Bengtsson <notifications@github.com>
Envoyé : jeudi 12 novembre 2020 19:49
À : samWieczorek/DAPAR <DAPAR@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [samWieczorek/DAPAR] Is R (>= 4.0.3) required for this package, or would R (>= 4.0.0) be sufficient? (#8)


Hi, I just noticed that DAPAR does not install on R 4.0.2. I see that for Bioc devel<http://bioconductor.org/packages/devel/bioc/html/DAPAR.html>, you've still got R (>= 4.0.0) but for Bioc release<http://bioconductor.org/packages/release/bioc/html/DAPAR.html> you've got R (>= 4.0.3).

Is R (>= 4.0.3) a hard requirement for this package? Note that Bioconductor 3.12 does not require R 4.0.3, cf. Bioconductor/bioconductor.org#76<https://github.com/Bioconductor/bioconductor.org/issues/76>. I run lots of revdep checks on CRAN and Bioc packages for my 'future' package and this far DAPAR is the only one that's a blocker on R 4.0.2.

PS. Yes, I know how to upgrade to R 4.0.3; I'm thinking of all the academic cluster users etc. out there still stuck on R 4.0.0.

**Comment by HenrikBengtsson** [comment]
FYI, this was mostly a question of whether your package has code that requires R (>= 4.0.3) but fails with R (>= 4.0.0).  I wanted to report that it might be a blocker for some people who wish to use DAPAR or one of its reverse dependencies, i.e.

```r
> pkgs <- tools::dependsOnPkgs("DAPAR", dependencies="all", installed=available.packages())
> str(pkgs)
 chr [1:2] "Prostar" "DAPARdata"
```

(In my case, it's the reverse dependency check of 'Prostar' that cannot be completed).

> ... I have to follow general rules for developers in Bioconductor.

Where are those "general rules"?  As you see from Martin's comment, R (>= 4.0.3) is not a hard dependency for Bioc 3.12.  I find the ambiguity in what's required for Bioc 3.12 unfortunately but that's a discussion for elsewhere.  FYI, among all CRAN(*) and Bioconductor packages, it just DAPAR and idpr that has this;

```r
> db <- as.data.frame(available.packages())
> db[grep("R [(]>= 4[.]0[.][123]", db$Depends), c("Package", "Version", "Repository")]
      Package Version                                              Repository
DAPAR   DAPAR  1.22.1 https://bioconductor.org/packages/3.12/bioc/src/contrib
idpr     idpr   1.0.0 https://bioconductor.org/packages/3.12/bioc/src/contrib
```

(*) CRAN doesn't allow for dependency on a specific patched version, i.e. you must only specify dependency like `R (>= x.y.0)` on CRAN, so this is mostly an issue on Bioconductor.

> But DAPAR should work with R >= 4.0.0. May I ask you how you install the packages you want to test ? There is a workaround to install DAPAR (for example) on R-4.0.2. You have to manually modify the DESCRIPTION file and change the version of R. Then, you have to rebuild the package on your computer and it will be ready to be installed on previous R versions.

Yes, I understand how to work around but I'm running revdep on 145+ packages on a regular basis on **future**, but also on several other packages, so I won't have the time to do such manual tweaks.  FWIW, I use the **[revdepcheck](https://github.com/r-lib/revdepcheck)** for this process.   This is not a biggy - revdepcheck will just skip tests on packages that it cannot test, which in my case is Prostar.

Cheers. Closing.
